version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"
    ports:
      - "{{POSTGRES_PORT}}:{{POSTGRES_PORT}}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "{{ PGADMIN_EMAIL }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ PGADMIN_PASSWORD }}"
    ports:
      - "{{PGADMIN_PORT}}:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
